"""add_recharge_cards_table

Revision ID: 039df70ac954
Revises: f5f02ea55179
Create Date: 2026-05-21 21:30:10.200234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039df70ac954'
down_revision = 'f5f02ea55179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recharge_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recharge_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recharge_cards_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recharge_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recharge_cards_code'))

    op.drop_table('recharge_cards')
    # ### end Alembic commands ###
