"""Add GeocodingTask and AddressLog tables

Revision ID: f5f02ea55179
Revises: 418aa4f4a6f7
Create Date: 2025-10-17 21:55:32.263123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f02ea55179'
down_revision = '418aa4f4a6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocoding_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geocoding_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geocoding_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_geocoding_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('address_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('address_keyword', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['geocoding_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_logs_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_logs_task_id'))

    op.drop_table('address_logs')
    with op.batch_alter_table('geocoding_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geocoding_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_geocoding_tasks_created_at'))

    op.drop_table('geocoding_tasks')
    # ### end Alembic commands ###
